INSERT INTO developers (name) VALUES ('1-UP Studio');
INSERT INTO developers (name) VALUES ('4J Studios');
INSERT INTO developers (name) VALUES ('Activision Shanghai');
INSERT INTO developers (name) VALUES ('Against Gravity');
INSERT INTO developers (name) VALUES ('AGM Playism');
INSERT INTO developers (name) VALUES ('Amplitude Studios');
INSERT INTO developers (name) VALUES ('Anegar Games');
INSERT INTO developers (name) VALUES ('Arika Co., Ltd.');
INSERT INTO developers (name) VALUES ('Arrowhead Game Studios');
INSERT INTO developers (name) VALUES ('Asobo Studio');
INSERT INTO developers (name) VALUES ('Aspyr Media, Inc.');
INSERT INTO developers (name) VALUES ('Backbone Entertainment');
INSERT INTO developers (name) VALUES ('Bae Team');
INSERT INTO developers (name) VALUES ('Bandai Namco Entertainment');
INSERT INTO developers (name) VALUES ('Beat Games');
INSERT INTO developers (name) VALUES ('Beenox Studios');
INSERT INTO developers (name) VALUES ('Beethoven & Dinosaur');
INSERT INTO developers (name) VALUES ('Ben Esposito');
INSERT INTO developers (name) VALUES ('BioWare');
INSERT INTO developers (name) VALUES ('Blacklight Interactive');
INSERT INTO developers (name) VALUES ('BlitWorks');
INSERT INTO developers (name) VALUES ('Blizzard Albany');
INSERT INTO developers (name) VALUES ('Budcat Creations');
INSERT INTO developers (name) VALUES ('Bulkhead Interactive');
INSERT INTO developers (name) VALUES ('Buzz Monkey Software, LLC');
INSERT INTO developers (name) VALUES ('CAProductions Co. Ltd.');
INSERT INTO developers (name) VALUES ('Cardboard Computer');
INSERT INTO developers (name) VALUES ('Cellar Door Games');
INSERT INTO developers (name) VALUES ('Chucklefish Games');
INSERT INTO developers (name) VALUES ('Clever Beans');
INSERT INTO developers (name) VALUES ('Code Mystics');
INSERT INTO developers (name) VALUES ('Codemasters');
INSERT INTO developers (name) VALUES ('Coffee Stain Studios');
INSERT INTO developers (name) VALUES ('Colossal Order');
INSERT INTO developers (name) VALUES ('ConcernedApe');
INSERT INTO developers (name) VALUES ('Cozy Cabin Studios');
INSERT INTO developers (name) VALUES ('Cradle Games');
INSERT INTO developers (name) VALUES ('Criterion Games');
INSERT INTO developers (name) VALUES ('Crytek');
INSERT INTO developers (name) VALUES ('Dani');
INSERT INTO developers (name) VALUES ('Daniel Mullins Games');
INSERT INTO developers (name) VALUES ('Deck Nine Games');
INSERT INTO developers (name) VALUES ('DICE');
INSERT INTO developers (name) VALUES ('Digital Eclipse Software, Inc.');
INSERT INTO developers (name) VALUES ('Digital Hearts Co., Ltd.');
INSERT INTO developers (name) VALUES ('Dodge Roll');
INSERT INTO developers (name) VALUES ('Dont Nod');
INSERT INTO developers (name) VALUES ('DotEmu');
INSERT INTO developers (name) VALUES ('Double Eleven');
INSERT INTO developers (name) VALUES ('Double Fine Productions, Inc.');
INSERT INTO developers (name) VALUES ('Downpour Interactive');
INSERT INTO developers (name) VALUES ('DrinkBox Studios');
INSERT INTO developers (name) VALUES ('EA Canada');
INSERT INTO developers (name) VALUES ('EA Tiburon');
INSERT INTO developers (name) VALUES ('EA Vancouver');
INSERT INTO developers (name) VALUES ('Eagle Dynamics');
INSERT INTO developers (name) VALUES ('Eighting Co., Ltd.');
INSERT INTO developers (name) VALUES ('Empyrean');
INSERT INTO developers (name) VALUES ('Enhance');
INSERT INTO developers (name) VALUES ('Epic Games');
INSERT INTO developers (name) VALUES ('EPOS Game Studios');
INSERT INTO developers (name) VALUES ('Evil Empire');
INSERT INTO developers (name) VALUES ('Extremely OK Games');
INSERT INTO developers (name) VALUES ('Flix Interactive');
INSERT INTO developers (name) VALUES ('Four Quarters');
INSERT INTO developers (name) VALUES ('Frictional Games');
INSERT INTO developers (name) VALUES ('FromSoftware, Inc.');
INSERT INTO developers (name) VALUES ('Frozen District');
INSERT INTO developers (name) VALUES ('Fullbright');
INSERT INTO developers (name) VALUES ('Game Freak, Inc.');
INSERT INTO developers (name) VALUES ('Ghost Town Games');
INSERT INTO developers (name) VALUES ('Giant Sparrow');
INSERT INTO developers (name) VALUES ('Giant Squid');
INSERT INTO developers (name) VALUES ('GIANTS Software GmbH');
INSERT INTO developers (name) VALUES ('Greg Lobanov');
INSERT INTO developers (name) VALUES ('HAL Laboratory, Inc.');
INSERT INTO developers (name) VALUES ('Halo Studios');
INSERT INTO developers (name) VALUES ('Hardsuit Labs');
INSERT INTO developers (name) VALUES ('Harmonix Music Systems');
INSERT INTO developers (name) VALUES ('Hazelight');
INSERT INTO developers (name) VALUES ('Heart Machine');
INSERT INTO developers (name) VALUES ('Helder Pinto');
INSERT INTO developers (name) VALUES ('Hello Games');
INSERT INTO developers (name) VALUES ('Hopoo Games');
INSERT INTO developers (name) VALUES ('Hudson Entertainment, Inc.');
INSERT INTO developers (name) VALUES ('id Software');
INSERT INTO developers (name) VALUES ('Image & Form');
INSERT INTO developers (name) VALUES ('Infinity Ward');
INSERT INTO developers (name) VALUES ('Innersloth');
INSERT INTO developers (name) VALUES ('Insomniac Games');
INSERT INTO developers (name) VALUES ('Intelligent Systems Co., Ltd.');
INSERT INTO developers (name) VALUES ('Iron Galaxy Studios');
INSERT INTO developers (name) VALUES ('Iron Gate Studios');
INSERT INTO developers (name) VALUES ('Jackbox Games');
INSERT INTO developers (name) VALUES ('Jason Roberts');
INSERT INTO developers (name) VALUES ('JW, Kitty, Jukio, Dom');
INSERT INTO developers (name) VALUES ('Klei Entertainment Inc.');
INSERT INTO developers (name) VALUES ('Landfall Games');
INSERT INTO developers (name) VALUES ('LucasArts Entertainment Company LLC');
INSERT INTO developers (name) VALUES ('Massive Monster');
INSERT INTO developers (name) VALUES ('Maxint LLC');
INSERT INTO developers (name) VALUES ('Mediatonic');
INSERT INTO developers (name) VALUES ('Mega Crit');
INSERT INTO developers (name) VALUES ('Mintrocket');
INSERT INTO developers (name) VALUES ('Mobius Games');
INSERT INTO developers (name) VALUES ('Modern Storyteller');
INSERT INTO developers (name) VALUES ('Mojang AB');
INSERT INTO developers (name) VALUES ('Monolith Software, Inc.');
INSERT INTO developers (name) VALUES ('Monomi Park');
INSERT INTO developers (name) VALUES ('Monstars Inc.');
INSERT INTO developers (name) VALUES ('Moon Studios');
INSERT INTO developers (name) VALUES ('Mossmouth, LLC');
INSERT INTO developers (name) VALUES ('Motion Twin');
INSERT INTO developers (name) VALUES ('Motive Studios');
INSERT INTO developers (name) VALUES ('Namco');
INSERT INTO developers (name) VALUES ('Naughty Dog, Inc.');
INSERT INTO developers (name) VALUES ('Neverjam');
INSERT INTO developers (name) VALUES ('Night School Studio');
INSERT INTO developers (name) VALUES ('Ninja Theory');
INSERT INTO developers (name) VALUES ('Nintendo Cube');
INSERT INTO developers (name) VALUES ('Nintendo EAD');
INSERT INTO developers (name) VALUES ('Nintendo EPD');
INSERT INTO developers (name) VALUES ('Nintendo R&D1');
INSERT INTO developers (name) VALUES ('Nintendo Software Technology Corporation');
INSERT INTO developers (name) VALUES ('Nixxes Software BV');
INSERT INTO developers (name) VALUES ('Nolla Games');
INSERT INTO developers (name) VALUES ('Oblix LLC');
INSERT INTO developers (name) VALUES ('Obsidian Entertainment');
INSERT INTO developers (name) VALUES ('Oculus Studios');
INSERT INTO developers (name) VALUES ('Origame Digital');
INSERT INTO developers (name) VALUES ('Other Ocean Interactive');
INSERT INTO developers (name) VALUES ('Outsource Media (OMUK)');
INSERT INTO developers (name) VALUES ('Pandemic Studios');
INSERT INTO developers (name) VALUES ('Panic Button');
INSERT INTO developers (name) VALUES ('Paradox Development Studio');
INSERT INTO developers (name) VALUES ('Pax Softnica');
INSERT INTO developers (name) VALUES ('People Can Fly');
INSERT INTO developers (name) VALUES ('Perfectly Paranormal');
INSERT INTO developers (name) VALUES ('Phobia Game Studio');
INSERT INTO developers (name) VALUES ('PigeoNation Inc.');
INSERT INTO developers (name) VALUES ('Pillow Castle Games');
INSERT INTO developers (name) VALUES ('Pixile');
INSERT INTO developers (name) VALUES ('Player First Games');
INSERT INTO developers (name) VALUES ('PlayEveryWare');
INSERT INTO developers (name) VALUES ('Playful Corp');
INSERT INTO developers (name) VALUES ('Playground Games');
INSERT INTO developers (name) VALUES ('PlayStation Studios');
INSERT INTO developers (name) VALUES ('Polyarc Games');
INSERT INTO developers (name) VALUES ('Psyonix Studios');
INSERT INTO developers (name) VALUES ('Q-Games');
INSERT INTO developers (name) VALUES ('QLOC');
INSERT INTO developers (name) VALUES ('RageSquid');
INSERT INTO developers (name) VALUES ('Rainbite Limited');
INSERT INTO developers (name) VALUES ('Rare, Ltd.');
INSERT INTO developers (name) VALUES ('Raw Thrills');
INSERT INTO developers (name) VALUES ('Ready at Dawn Studios, LLC');
INSERT INTO developers (name) VALUES ('Red Dot Games');
INSERT INTO developers (name) VALUES ('Relic Entertainment');
INSERT INTO developers (name) VALUES ('Remedy Entertainment Ltd.');
INSERT INTO developers (name) VALUES ('Resonair');
INSERT INTO developers (name) VALUES ('Respawn Entertainment');
INSERT INTO developers (name) VALUES ('Ripple Effect');
INSERT INTO developers (name) VALUES ('SCE XDev Studio');
INSERT INTO developers (name) VALUES ('Sealost Interactive LLC');
INSERT INTO developers (name) VALUES ('Sega');
INSERT INTO developers (name) VALUES ('Shedworks');
INSERT INTO developers (name) VALUES ('Shiny Shoe');
INSERT INTO developers (name) VALUES ('Shloc Ltd.');
INSERT INTO developers (name) VALUES ('Sickhead Games');
INSERT INTO developers (name) VALUES ('SIE Japan Studio');
INSERT INTO developers (name) VALUES ('SIE Santa Monica Studio');
INSERT INTO developers (name) VALUES ('Slightly Mad Studios');
INSERT INTO developers (name) VALUES ('Sloclap');
INSERT INTO developers (name) VALUES ('Sonic Mayhem');
INSERT INTO developers (name) VALUES ('Sora');
INSERT INTO developers (name) VALUES ('Sports Interactive Limited');
INSERT INTO developers (name) VALUES ('SRD Co. Ltd.');
INSERT INTO developers (name) VALUES ('Stage Games');
INSERT INTO developers (name) VALUES ('Studio MDHR');
INSERT INTO developers (name) VALUES ('Subset Games');
INSERT INTO developers (name) VALUES ('Sucker Punch');
INSERT INTO developers (name) VALUES ('Supergiant Games');
INSERT INTO developers (name) VALUES ('SuperJoeBob');
INSERT INTO developers (name) VALUES ('Survios');
INSERT INTO developers (name) VALUES ('Sweet Baby Inc.');
INSERT INTO developers (name) VALUES ('System Era Softworks');
INSERT INTO developers (name) VALUES ('Tantalus Media');
INSERT INTO developers (name) VALUES ('Team Cherry');
INSERT INTO developers (name) VALUES ('Team17 Software Limited');
INSERT INTO developers (name) VALUES ('Techland Sp. z o.o.');
INSERT INTO developers (name) VALUES ('Teknopants');
INSERT INTO developers (name) VALUES ('The Game Bakers');
INSERT INTO developers (name) VALUES ('The Molasses Flood');
INSERT INTO developers (name) VALUES ('The Munky');
INSERT INTO developers (name) VALUES ('Thunder Lotus Games');
INSERT INTO developers (name) VALUES ('Tomas Sala');
INSERT INTO developers (name) VALUES ('Toys for Bob');
INSERT INTO developers (name) VALUES ('Travellers Tales Ltd.');
INSERT INTO developers (name) VALUES ('TT Fusion');
INSERT INTO developers (name) VALUES ('TT Games');
INSERT INTO developers (name) VALUES ('Two Point Studios');
INSERT INTO developers (name) VALUES ('Ubisoft Annecy Studios');
INSERT INTO developers (name) VALUES ('Ubisoft Ivory Tower');
INSERT INTO developers (name) VALUES ('Ubisoft Kiev');
INSERT INTO developers (name) VALUES ('Ubisoft Montpellier Studios');
INSERT INTO developers (name) VALUES ('Ubisoft Reflections');
INSERT INTO developers (name) VALUES ('Undead Labs');
INSERT INTO developers (name) VALUES ('Unknown Worlds');
INSERT INTO developers (name) VALUES ('Valve Corporation');
INSERT INTO developers (name) VALUES ('Vanillaware Ltd.');
INSERT INTO developers (name) VALUES ('Vertigo Gaming Inc.');
INSERT INTO developers (name) VALUES ('Villa Gorilla');
INSERT INTO developers (name) VALUES ('Virtuos Ltd.');
INSERT INTO developers (name) VALUES ('VRChat Inc.');
INSERT INTO developers (name) VALUES ('WanadevStudio');
INSERT INTO developers (name) VALUES ('WeirdBeard');
INSERT INTO developers (name) VALUES ('Were Five Games');
INSERT INTO developers (name) VALUES ('Whirlybird Games');
INSERT INTO developers (name) VALUES ('Xbox Game Studios');
INSERT INTO developers (name) VALUES ('Zenimax Media Inc');
INSERT INTO developers (name) VALUES ('Zillion Whales');
