INSERT INTO genres (name) VALUES ('Action-Adventure');
INSERT INTO genres (name) VALUES ('Brawler');
INSERT INTO genres (name) VALUES ('Card Game');
INSERT INTO genres (name) VALUES ('Compilation');
INSERT INTO genres (name) VALUES ('Driving/Racing');
INSERT INTO genres (name) VALUES ('Dual-Joystick Shooter');
INSERT INTO genres (name) VALUES ('Educational');
INSERT INTO genres (name) VALUES ('First-Person Shooter');
INSERT INTO genres (name) VALUES ('Fishing');
INSERT INTO genres (name) VALUES ('Flight Simulator');
INSERT INTO genres (name) VALUES ('Golf');
INSERT INTO genres (name) VALUES ('Minigame Collection');
INSERT INTO genres (name) VALUES ('Platformer');
INSERT INTO genres (name) VALUES ('Puzzle');
INSERT INTO genres (name) VALUES ('Role-Playing');
INSERT INTO genres (name) VALUES ('Shoot ''Em Up');
INSERT INTO genres (name) VALUES ('Shooter');
INSERT INTO genres (name) VALUES ('Simulation');
INSERT INTO genres (name) VALUES ('Snowboarding/Skiing');
INSERT INTO genres (name) VALUES ('Soccer');
INSERT INTO genres (name) VALUES ('Sports');
INSERT INTO genres (name) VALUES ('Strategy');
INSERT INTO genres (name) VALUES ('Tennis');
INSERT INTO genres (name) VALUES ('Text Adventure');
INSERT INTO genres (name) VALUES ('Vehicular Combat');
INSERT INTO genres (name) VALUES ('Action');
INSERT INTO genres (name) VALUES ('Adventure');
INSERT INTO genres (name) VALUES ('Fighting');
INSERT INTO genres (name) VALUES ('Football');
INSERT INTO genres (name) VALUES ('Music/Rhythm');
INSERT INTO genres (name) VALUES ('Pinball');
INSERT INTO genres (name) VALUES ('Real-Time Strategy');
INSERT INTO genres (name) VALUES ('Skateboarding');
INSERT INTO genres (name) VALUES ('Trivia/Board Game');