INSERT INTO genres (name) VALUES ('Abstract');
INSERT INTO genres (name) VALUES ('Adult');
INSERT INTO genres (name) VALUES ('Alternate Historical');
INSERT INTO genres (name) VALUES ('Anime');
INSERT INTO genres (name) VALUES ('Aquatic');
INSERT INTO genres (name) VALUES ('Comedy');
INSERT INTO genres (name) VALUES ('Comic Book');
INSERT INTO genres (name) VALUES ('Crime');
INSERT INTO genres (name) VALUES ('Cyberpunk');
INSERT INTO genres (name) VALUES ('Dating');
INSERT INTO genres (name) VALUES ('Espionage');
INSERT INTO genres (name) VALUES ('Fantast');
INSERT INTO genres (name) VALUES ('Fantasy');
INSERT INTO genres (name) VALUES ('Game Show');
INSERT INTO genres (name) VALUES ('Horror');
INSERT INTO genres (name) VALUES ('Management');
INSERT INTO genres (name) VALUES ('Martial Arts');
INSERT INTO genres (name) VALUES ('Mayan');
INSERT INTO genres (name) VALUES ('Medieval');
INSERT INTO genres (name) VALUES ('Modern Military');
INSERT INTO genres (name) VALUES ('Motorsports');
INSERT INTO genres (name) VALUES ('Post-Apocalyptic');
INSERT INTO genres (name) VALUES ('Prehistoric');
INSERT INTO genres (name) VALUES ('Sci-Fi');
INSERT INTO genres (name) VALUES ('Steampunk');
INSERT INTO genres (name) VALUES ('Superhero');
INSERT INTO genres (name) VALUES ('Western');
INSERT INTO genres (name) VALUES ('World War II');